version: '3.4'

services:
      chatdb:
            container_name: chatdb
            restart: always
            volumes:
                - ${WEBAPP_STORAGE_HOME}/site:/data/db
            ports:
                - "1433:1433"
      chatapi:
            environment:
                 - ASPNETCORE_ENVIRONMENT=Development
                 - ASPNETCORE_URLS=https://+:443;http://+:80
                 - "ConnectionStrings:ChatDb=Server=chatdb;Database=ChatDb;User Id=SA;Password=Pa55w0rd2020"

            depends_on:
                - chatdb

            volumes:
                - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
                - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
                
            ports:
                - "8001:443"
            

      