version: '3.4'

services:
    chatdb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pa55w0rd2020"
            ACCEPT_EULA: "Y"
    chatapi:
        image: ${DOCKER_REGISTRY-}chatapi
        build:
            context: .
            dockerfile: ChatAPI/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development

