version: '3.4'

services:
      chatdb:
            container_name: chatdb
            restart: always
            volumes:
                - ${WEBAPP_STORAGE_HOME}/site:/data/db
            ports:
                - "1433:1433"
      chatapi:
            environment:
                - ASPNETCORE_ENVIRONMENT=Development
                - ASPNETCORE_URLS=https://+:443;http://+:80
                
            ports:
                - "8000:80"
            depends_on:
                - chatdb

      