version: '3.4'

services:
      chatdb:
            container_name: chatdb
            restart: always
            volumes:
                - ${WEBAPP_STORAGE_HOME}/site:/data/db
            ports:
                - "1433:1433"
      chatapi:
            environment:
                 - ASPNETCORE_ENVIRONMENT=Development


            depends_on:
                - chatdb

            volumes:
                - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
                - ${HOME}/.aspnet/https:/root/.aspnet/https/
                
            ports:
                - "8000:80"
            

      